version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/django.Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - scraper

  scraper:
    build:
      context: .
      dockerfile: docker/scrapers.Dockerfile
    environment:
      - PYTHONPATH=/app/src
    volumes:
      - .:/app
    depends_on:
      - redis
    entrypoint: celery -A worker.tasks worker --loglevel=INFO

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"