# Generated by Django 5.0.1 on 2024-02-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('scrape_status', models.CharField(choices=[('Scraping', 'Scraping'), ('Scraped', 'Scraped'), ('Failed', 'Failed'), ('Disabled', 'Disabled')], default='Scraping', max_length=100)),
                ('title', models.CharField(max_length=100, null=True)),
                ('single_file_html_path', models.FilePathField(null=True, path='/', recursive=True)),
                ('media_path', models.FilePathField(null=True, path='/', recursive=True)),
            ],
        ),
    ]
