# Generated by Django 5.0.1 on 2024-02-04 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_bookmark_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='scrape_status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Scraping', 'Scraping'), ('Scraped', 'Scraped'), ('Failed', 'Failed'), ('Disabled', 'Disabled')], default='Initial', max_length=100),
        ),
    ]
