# Generated by Django 5.0.1 on 2024-02-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_bookmark_scrape_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='media_status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Scraping', 'Scraping'), ('Scraped', 'Scraped'), ('Failed', 'Failed'), ('Disabled', 'Disabled')], default='Initial', max_length=100),
        ),
    ]
