# Generated by Django 5.0.1 on 2024-02-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_bookmark_media_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='media_path',
            field=models.FilePathField(max_length=256, null=True, path='/', recursive=True),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='media_status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Scraping', 'Scraping'), ('Scraped', 'Scraped'), ('Failed', 'Failed'), ('Disabled', 'Disabled')], default='Initial', max_length=16),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='scrape_status',
            field=models.CharField(choices=[('Initial', 'Initial'), ('Scraping', 'Scraping'), ('Scraped', 'Scraped'), ('Failed', 'Failed'), ('Disabled', 'Disabled')], default='Initial', max_length=16),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='single_file_html_path',
            field=models.FilePathField(max_length=256, null=True, path='/', recursive=True),
        ),
    ]
